version: '3.9'
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5532
    expose:
      - 5532
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_glpi
    command: ["/fastapi_glpi/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db