version: '3.9'

services:
  db:
    container_name: "db"
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - 5532:5532
    command:
      - "postgres"
      - "-c"
      - "port=5532"
    networks:
      - custom
  
  app:
    build:
     context: .
    env_file:
    - .env
    container_name: fastapi_glpi
    command: [ "/fastapi_glpi/docker/app.sh" ]
    ports:
     - 9999:8000
    depends_on:
     - db
    networks:
      - custom

networks:
  custom:
    driver: bridge

